

---- CREAR TABLA SILVER -- CLIENTES

CREATE OR REFRESH STREAMING TABLE IDENTIFIER('${CATALOG}.ly_silver.CLIENTS') (
    ---- QUALITY CONSTRAINTS
    CONSTRAINT VALID_CLIENT_ID EXPECT ( CLIENT_ID IS NOT NULL) ON VIOLATION FAIL UPDATE,
    CONSTRAINT NOT_NULL_EMAIL EXPECT ( EMAIL IS NOT NULL) 
) AS 
SELECT 
    * EXCEPT (SOURCE_FILE)
FROM STREAM (${CATALOG}.ly_bronze.CLIENTS_RW) ;


----- DEFINIR TABLA ORDERS

CREATE OR REFRESH STREAMING TABLE IDENTIFIER('${CATALOG}.ly_silver.ORDERS') (
    --- SCHEMA 
    ORDER_ID STRING,
    ORDER_TIMESTAMP TIMESTAMP,
    CLIENT_ID STRING,
    CATEGORY STRING,
    TOTAL_QTY INTEGER,
    TOTAL_PRICE DECIMAL(10, 2),
    SOURCE_FILE STRING,
    IS_QUARANTINED BOOLEAN,
    QUARANTINE_REASON STRING
    
    ---- QUALITY CONSTRAINTS
    CONSTRAINT VALID_ORDER_ID EXPECT ( ORDER_ID IS NOT NULL) ON VIOLATION FAIL UPDATE,
    CONSTRAINT VALID_CLIENT EXPECT (CLIENT_ID RLIKE '^CLI[0-9]+$'),
    CONSTRAINT TOTAL_QTY_POS EXPECT ((TOTAL_QTY >= 0) OR (TOTAL_PRICE >= 0))
);


CREATE FLOW APPEND_ORDERS_QITH_QA_LOGIC 
AS 
INSERT INTO IDENTIFIER('${CATALOG}.ly_silver.ORDERS') BY NAME
SELECT  
    ORDER_ID,
    ORDER_TIMESTAMP,
    CLIENT_ID,
    CATEGORY,
    TOTAL_QTY,
    CAST( TOTAL_PRICE AS DECIMAL(10,2) ) AS TOTAL_PRICE,
    SOURCE_FILE,
    NOT ( (ORDER_ID IS NOT NULL)
    AND (CLIENT_ID RLIKE '^CLI[0-9]+$')
    AND (TOTAL_QTY >= 0) 
    AND (TOTAL_PRICE >= 0)
    ) AS IS_QUARANTINED,
    concat_ws("; ",
        CASE WHEN ORDER_ID IS NULL THEN 'ORDER_ID SIN ID' END,
        CASE WHEN CLIENT_ID NOT RLIKE '^CLI[0-9]+$' THEN 'CODIGO DE CLIENTES ERRONEO' END,
        CASE WHEN TOTAL_QTY < 0 OR total_price < 0 THEN 'TOTAL_QTY NEGATIVO' END
        ) AS QUARANTINE_REASON
FROM STREAM (${CATALOG}.ly_bronze.ORDERS_RW) ;

------ ORDERS CLEANED 

CREATE OR REFRESH STREAMING TABLE IDENTIFIER('${CATALOG}.ly_silver.ORDERS_CLEANED')
COMMENT 'Registros que pasan las validaciones de calidad'
AS 
SELECT * EXCEPT ( IS_QUARANTINED, QUARANTINE_REASON, SOURCE_FILE)
FROM STREAM (${CATALOG}.ly_silver.ORDERS)
WHERE IS_QUARANTINED = false;


------ QUARANTINE TABLE 

CREATE OR REFRESH STREAMING TABLE IDENTIFIER('${CATALOG}.ly_silver.ORDERS_QUARANTINED')
COMMENT 'Registros que fallan alguna de las validaciones de calidad'
TBLPROPERTIES(
    'pipeline.reset,allowed' = FALSE
)
AS 
SELECT *,
    CURRENT_DATE AS INS_DATE
FROM STREAM (${CATALOG}.ly_silver.ORDERS)
WHERE IS_QUARANTINED = TRUE;



