
----- MATERIALIZED VIEW
USE CATALOG ${CATALOG} ;

CREATE OR REFRESH MATERIALIZED VIEW  ly_gold.ORDER_BY_CITY
AS
SELECT 
    C.STATE,
    C.CITY,
    COUNT(O.*) TOTAL_ORDERS,
    SUM(O.TOTAL_QTY) as TOTAL_QTY,
    SUM(O.TOTAL_PRICE) AS TOTAL_PRICE
FROM (${CATALOG}.ly_silver.ORDERS_CLEANED) O
LEFT JOIN (${CATALOG}.ly_silver.CLIENTS) C
    USING (CLIENT_ID)
GROUP BY C.STATE, C.CITY ;

---- AUTO CDC

CREATE OR REFRESH STREAMING TABLE ly_gold.CLIENTS_CURATED (
    CLIENT_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    ZIP_CODE INTEGER,
    FILE_MOD_TIME TIMESTAMP,
    __START_AT TIMESTAMP,
    __END_AT TIMESTAMP
);

CREATE FLOW APPLY_CDC_CLIENTS 
AS AUTO CDC
INTO ly_gold.CLIENTS_CURATED
FROM STREAM(ly_silver.CLIENTS)
KEYS (CLIENT_ID)
SEQUENCE BY FILE_MOD_TIME
STORED AS SCD TYPE 2
TRACK HISTORY ON FIRST_NAME, LAST_NAME, EMAIL, PHONE, CITY, STATE, ZIP_CODE
;